In [2]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()

url = 'https://cafe.naver.com/joongonara'

driver.get(url)

select = "자전거"

elem = driver.find_element(By.ID,'topLayerQueryInput')
elem.send_keys(select)
elem.send_keys(Keys.RETURN)

sub_url = "/ArticleSearchList.nhn?search.clubid=13208786&search.searchBy=0&search.query=%C0%DA%C0%FC%B0%C5"
main_url = 'https://cafe.naver.com/joongonara'
result_url = main_url + sub_url

# 1. webdriver를 main_url로 이동, page_source
# 2. main_url로 request

# 원본 소스가 있는 웹으로 이동
driver.switch_to.frame('cafe_main')

elems = driver.find_elements(By.CSS_SELECTOR,'a.article')

In [5]:
for e in elems:
    print(e.text)
    
    print(e.get_attribute('href'))

자전거 카페 가입햇습니다 등업신청
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=510843&referrerAllArticles=true
등업신청합니다! 자전거카페도 가입완료^^
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=494039&referrerAllArticles=true
하이브리드 자전거 사실분 안계신가요?
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=490874&referrerAllArticles=true
자전거 미니벨로 티티카카 플라이트 P8팝니다
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=490287&referrerAllArticles=true
등업했어요 자전거카페도 가입했어요
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=490045&referrerAllArticles=true
출퇴근용으로 구입한 자전거인데 제가 키가 작아서 저한테는 너무 커서 판매할려고합니다
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=489783&referrerAllArticles=true
저스틴 하이브리트 자전거 10만원에 팝니다
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=489590&referrerAllArticles=true
자전거 팝니다!!!원가 25만원 이상되는데 20만원 정도에 팔께요 흥정같은건 생각해보겠습니다
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=488768&referrerAllArticles=true
초등학생 자전거 판매합니다
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=488600&referrerAllArticles=true
픽시자전거 2만원안에 구해봅니당~댓글에 톡디 남겨주세요~~
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=488010&referrerAllArticles=true
광교웰빙타운호반베르디움에서?초6에서?중1?학생?자전거?팝니다.자전거는?삼천리이고요?이름은?Lespo?Typhoon입니다.?가격은?40000원이고요.?가까이?사시는?분들이?직접?가져가시면?좋겠습니다.
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=487941&referrerAllArticles=true
자전거는 잘 모르지만 신품이 95만원 하는것으로 알고있습니다.
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=487622&referrerAllArticles=true
광교웰빙타운 호반베르디움에서 초6에서 중1학생 자전거팝니다.자전거는 삼천리이고요. 이름은 Lespo Typhoon입니다. 가격은 40000원이고요. 가까이 사시는 분들이 직접 가져가시면 좋겠습니다.
https://cafe.naver.com/ca-fe/ArticleRead.nhn?clubid=13208786&page=1&inCafeSearch=true&searchBy=1&query=%EC%9E%90%EC%A0%84%EA%B1%B0&includeAll=&exclude=&include=&exact=&searchdate=all&media=0&sortBy=date&articleid=486144&referrerAllArticles=true

In [ ]:
driver.switch_to.default_content() # 다시 main frame으로 돌아가기

In [8]:
# 삼성전자
# 네이버 증권
# 일별시세

import requests
from bs4 import BeautifulSoup
import pandas as pd

# selenium 임포트
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys 

# 못읽음
#res = requests.get(url)
#res.text
#dfs = pd.read_html(res.text)
#len(dfs)
#dfs[0]
#dfs = pd.read_html(html)
#dfs[10]

main_url = 'https://finance.naver.com'

driver = webdriver.Chrome()
driver.get(main_url)

html = driver.page_source
soup = BeautifulSoup(html, 'html.parser')

In [9]:
url = 'https://finance.naver.com/item/sise.naver?code=005930'
sub_url = '/item/sise_day.naver?code=005930'
full_url = main_url+ sub_url

#res = requests.get(full_url)

driver = webdriver.Chrome()
driver.get(full_url)

html = driver.page_source

data = pd.read_html(html)[0]
data.dropna(inplace=True)
data

            날짜       종가     전일비       시가       고가       저가         거래량
1   2023.12.04  72800.0   800.0  72800.0  72900.0  72500.0   3994681.0
2   2023.12.01  72000.0   800.0  72400.0  72500.0  71700.0   9871284.0
3   2023.11.30  72800.0   100.0  72700.0  72800.0  72200.0  15783714.0
4   2023.11.29  72700.0     0.0  72400.0  72800.0  72200.0   9283933.0
5   2023.11.28  72700.0  1400.0  71400.0  72700.0  71300.0  13283081.0
9   2023.11.27  71300.0   400.0  71500.0  72100.0  71100.0   9113857.0
10  2023.11.24  71700.0   700.0  72400.0  72600.0  71700.0   6676685.0
11  2023.11.23  72400.0   400.0  73000.0  73200.0  72200.0   6775614.0
12  2023.11.22  72800.0     0.0  72200.0  73000.0  71900.0  11105143.0
13  2023.11.21  72800.0   100.0  73100.0  73400.0  72700.0   9712881.0

In [ ]:
url = 'https://finance.naver.com/item/sise.naver?code=005930'

headers = {
    'Referer' : 'https://finance.naver.com/item/sise.naver?code=005930',
    'User-Agent:' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
}

res = requests.get(url, headers=headers)