In [1]:
# 1. 변수 a에 'hello world'를 할당한 후, a를 출력하시오
a = 'hello world'
print(a)

hello world

In [3]:
# 2. a에는 10, b에는 20을 입력한 후 사칙연산을 계산하시오
a = 10
b = 20

print(a + b)
print(a - b)
print(a * b)
print(a / b)

30
-10
200
0.5

In [4]:
# 3. 위의 문제에서 a를 b로 나눈 나머지를 계산하시오
print(a % b)

10

In [5]:
# 4. a의 b승을 계산하시오..
print(a ** b)

100000000000000000000

In [6]:
# 5. 위의 a의 데이터 타입을 출력하시오
type(a)

int

In [ ]:
# 6. a = '3'에서 a를 정수와 실수로 형변환하시오

In [ ]:
# 7. 원소 'a', '나','3', 4를 갖는 list를 생성하시오

In [ ]:
# 8. 위의 list를 문자열 string으로 변환하시오

In [ ]:
# 9. 8번에서 동일한 원소를 갖는 tuple과 set을 생성하시오

In [ ]:
# 10. 정수 54789을 문자열로 변환하시오.

In [ ]:
# 11
# key를 '가', '나', '다','라'를 순차적으로 갖고
# value를 'A', 'B', 'C', 'D'를 순차적으로 갖는 dictionary를 생성하시오..

In [ ]:
# 12

a = 2
b = 5
# a가 b보다 크거나 같은지 확인하시오
# a와 b가 같은지 확인하시오
# a가 b보다 작은지 확인하시오

In [ ]:
txt1 = 'A tale that was not right'

In [ ]:
#13. 'ale' 이 출력..

In [ ]:
# 14. 'A tale' 출력

In [ ]:
# 15. 'not' 출력 – split()함수를 활용하시오

In [ ]:
# 16. txt1을 소문자 전환

In [ ]:
# 17. txt1을 대문자 전환

In [ ]:
# 18. 'o'가 몇 개 존재하는가?

In [ ]:
# 19. 'o'가 몇 번 인덱스에 존재하는가?

In [ ]:
# 20. txt1의 길이는 어떻게 되는가?

In [ ]:
# 21. 'tale'을  'story'로 바꾸세요..

In [ ]:
# 22. txt1 안에 'right'가 존재하는지 확인

In [ ]:
# 23. space를 기준으로 나누어서 리스트에 담으시오.

In [ ]:
# 24. ~ 29.
lang = 'python programming'

# 'tho'
# 'pro'
# 'ming'
# 'n p'
# 'ing'
# 'python'

In [ ]:
# 30. 위의 두 문자열을 연결하시오

In [ ]:
# 31. 'hello'를 세 번 반복하시오

In [ ]:
# 32. lang에 's'가 있는지 확인하시오

In [ ]:
# 33. 이메일을 입력받은 후 id와 domain을 분리해서 출력하시오..

In [ ]:
# 34. 'hello python'에서 hello 대신 다른 단어가 들어갈 수 있도록 formatting을 만드시오

In [ ]:
# 35. 함수를 사용해서 'hello python'에서 'hello'를 'java'로 바꾸시오

In [10]:
# List

solarsys = ['태양', '수성', '금성', '지구', '화성', '목성', '지구']
solarsys1 = ['토성', '천왕성', '해왕성']
planet = '지구'

solarsys.find("지구")

AttributeError: 'list' object has no attribute 'find'

In [ ]:
# 36. solarsys 에서 ['수성', '금성', '지구'] 를 출력

In [9]:
# 37. solarsys에서 '지구'의 위치값 출력

AttributeError: 'list' object has no attribute 'find'

In [ ]:
# 38. solarsys에서 '화성'을 '해왕성'으로 수정

In [ ]:
# 39. solarsys에 '토성'을 맨 끝에 첨가

In [ ]:
# 40~ 55

#  solarsys에서 '수성' 자리에 '명왕성'을 삽입
#  solarsys에 맨 끝 요소를 제거하고 리턴
#  solarsys에서 '금성'을 제거
#  solarsys에서 1번째에서 3번째까지 살제
#  solarsys에서 인덱스값 2번 요소를 삭제
#  solarsys와 solarsys1을 합하시요.
#  solarsys를 오름차순으로 정력하세요.
#  solarsys를 내림차순으로 정렬하세요.
#  solarsys의 원소의 순서를 바꾸세요.
#  solarsys에 '만리장성'이 있는지 확인하세요.
#  solarsys를 3번 반복하세요.
#  solarsys의 길이를 리턴하세요.
#  solarsys에서 '지구'의 갯수를 출력하세요.
#  solarsys의 모든 원소를 지워세요.
#  solarsys 리스트를 삭제하세요.

In [ ]:
# 55문항 없음...

In [ ]:
# Tuple

myTuple = ("tuple", (1, 2, 3), [4, 5, 6])


#56. 'tuple'을 출력하시오

#57.  3을 출력하세요

#58 4, 5를 출력하세요

#59. 4를 출력하세요

#60. (1, 2, 3)을 출력하세요

In [ ]:
my_tuple = (1, 2, 3, 3, 2, 1)
your_tuple = (4, 5, 6)

# 튜플 연산
#61 my_tuple과 your_tuple을 연결하세요

#62 mytuple을 3번 반복하세요

#63 mytuple에 3이 있는지 확인하세요

#64 mytuple에 5가 있는지 확인하세요

#65 mytuple에서 1의 갯수를 출력하세요

#66 mytuple에서 index 2자리의 값을 출력하세요

In [ ]:
t_float = (120.09, 9.11, 2.8)
L_int = [1, 2, 3]


#67 ~ 73
# t_float의 길이를 출력하세요
# t_float의 최대값을 출력하세요
# t_float의 최소값을 출력하세요
# t_float의 합을 출력하세요.
# t_float의 평균을 출력하세요.
# t_float를 오름차순 정렬하세요

In [ ]:
#74 my_set이라는 빈 집합을 만들고 'sky','sea','earth' 세 요소를 추가하시오
my_set ={}

my_set.add

my_set.discard

In [ ]:
#75 ('1', '2')를 추가하시오
#76 sky'를 삭제하세요

In [ ]:
#77  모든 원소를 삭제하세요

In [ ]:
a = {1,2,3,4,5,6}
b = {1,3,4,7,8,9}

#78 두 집합의 합집합을 구하시오
#79 두 집합의 교집합을 구하시오
#80 집합 a의 b에 대한 차집합을 구하시오
#81 대칭차집합을 구하시오

In [ ]:
#82 a가 c를 포함하는지 확인하시오
#83 c가 a의 부분집합인지 확인하시오
#84 c와 b가 서로소인지 확인하시오

In [ ]:
#85 집합 a의 길이를 구하시오
#86 집합 b에 7이 포함되어 있는지 확인하시오.

In [ ]:
# 87~ 95

names = {'Mary':10999, 'Sams':2111, 'Aimy':9778, 'Tom':20245,
'Michale':27115, 'Bob':5887, 'Kelly':7855}



# Aimy의 value를 10000으로 수정하세요
# 'Sams'를 삭제하세요
# value 값들의 합을 구하세요
# value 값들의 최대값을 구하세요
# key값들을 출력하세요
# value값들을 출력하세요
# 키는 'Jane', 값은 5688인 요소를 추가하세요..
# name의 key와 valule를 쌍으로 묶어서 출력
# 모든 요소를 삭제하세요

In [ ]:
# 96~101

names = {'Mary':10999, 'Sams':2111, 'Aimy':9778, 'Tom':20245,
'Michale':27115, 'Bob':5887, 'Kelly':7855}

# names dict의 원소의 수를 출력하시오
# names의 key에 Tom이 있는지 확인하시오..
# names에서 Jane이 있으면 값을 출력하고, 없으면 0을 출력하시오.
# names의 값에 5887이 있는지 확인하시오.
# 이름을 입력받은 이름이 names에 있으면 값을 출력하고, 없으면 값 3000으로
#   names에 추가하시오

In [ ]:
# 102

# 성적을 입력받은 후 70이상이면 '합격입니다'를 출력
#                    70미만이면 '불합격입니다'를 출력

In [ ]:
# 103

pw = 7878

# 패스워드를 입력 받은 후 패스워드가 일치하면 '환영합니다', 일치하지 않으면
# '패스워드가 틀립니다'가 출력되도록 하시오.

In [ ]:
# 104 임의의 정수를 입력받은 후 짝수이면 "작수입니다"를 출력, 홀수이면 "홀수입니다"를 출력

In [ ]:
# 105

# 임의의 두 정수 a, b를 입력받은 후
# a가 b보다 크면, "a가 b보다 큽니다"
# a가 b보다 작으면, "a가 b보다 작습니다"
# a와 b가 같으면, "a와 b가 같습니다"를 출력하도록 하시오

In [ ]:
# 106

# 출생년도를 입력받은 후, (age = 현재년도 - 출생년도)
# 60세 이상이면 "노년이시군요"
# 40세 이상 60세 미만이면 "중년이신군요"
# 20세 이상 40세 미만이면 "청년이시군요"
# 20세 미만이면 "유년이시군요"를 출력

In [ ]:
# 107

# 점수를 입력받은 후 학점을 출력하는 코드를 작성하시오
# 90점 이상 => 'A학점입니다'
# 90점 미만 80점 이상 => 'B학점입니다'
# 80점 미만 70점 이상 => 'C학점입니다'
# 70점 미만 60점 이상 => 'D학점입니다'
# 60점 미만 => 'E학점입니다'

In [ ]:
# 108.
# L = ['a','b','c']
# # enumerate()을 사용하면서 L의 원소에 인덱스를 붙여서 원소를 출력한다

In [ ]:
# 109.
# names = ['철수', '영희', '민수', '경희']를 아래와 같이 출력하시오..
# # 1번 : 철수
# # 2번 : 영희
# # 3번 : 민수
# # 4번 : 경희

In [ ]:
# 110.
# # hello python을 for문을 이용해서 대문자로 바꿔서 출력하시오..

In [ ]:
# 111.
# d = {'a':1, 'b':2, 'c':3, 'd':4}
# # key와 value를 tuple로 묶어서 출력하시오. for문을 이용해서...

In [ ]:
# 112.
# # key와 value를 k_list, v_list라는 별도의 리스트에 나누어 담으시오. for문을 이용해서..

print(v_list)

In [ ]:
# 113.
# L1 = [1,2,3,4,5]
# L2 = [6,7,8,9]
# # L1과 L2의 모든 원소간의 곱을 total_list에 담으시오..
# # 이중 for문을 사용..

In [ ]:
# 114.
# # 1부터 20까지 정수에서 짝수들의 합을 출력하시오.. for문을 이용하시오..

In [ ]:
# 115.
# L1 = ['a','b','c','d','e']
# # for문을 이용해서 L1의 값을 dict에 담으시오..
# # d = {1:'a', 2:'b', 3:'c', 4:'d'}

In [ ]:
# 116.
# # text = 'python programming'에서 모음만 list에 담으시오. 단, 모음은 'aeiou'

In [ ]:
# 117.
# # L1 = ['a','b','c','d','e']
# # L2 = ['가', '나', '다', '라', '마']
# # 두 리스트의 모든 조합을 튜플로 묶어서 리스트에 담으시오..
# # => [('a', '가'), ('a', '나'), ('a', '다'), ... , ('e', '라'), ('e', '마')]

In [ ]:
# 117-1
# # 일반  for문으로

In [ ]:
# 117-2
# # list comprehension으로

In [ ]:
# 118.
# #  1부터 10까지 짝수만 리스트에 담으시오... list comprehension으로

In [ ]:
# 119.

# lst = ['apple', 'banana', 'cherry', 'durian', 'elderberry']
# # 각 단어의 길이를 리스트에 담으시오.
# # char_len = []
# # 각각 일반 for문과 list comprehension으로 만드시오..

In [ ]:
# 120.
# # 1 ~ 20까지 정수에서 3의 배수를 출력하시오.. while문으로..

In [ ]:
# 121
# # while문으로 1부터 10까지 출력하면서 continue를 통해서 3의 배수를 제외하시오
# 반복문에서 continue를 만나면 반복 처음으로 돌아간다..

In [ ]:
# 122.
# # while문에서 1부터 10까지 출력하는 코드에서, break와 continue를 사용해서
# 3 ~ 5까지만 출력하도록 하시오..

In [ ]:
# 123.
# # while문을 이용해서 점수를 5회 입력받은 후, 점수의 평균을 출력하시오..

In [ ]:
# 124 매개변수로 임의의 정수를 입력받은 후 절대값을 리턴하는 함수 "abs()"를 사용자정의함수로 만들고 실행하시오

In [ ]:

#125
# 임의의 정수를 받다서 짝수인지 홀수인지를 출력하는 함수..
# 짝수면 1리턴, 홀수면 0을 리턴..

In [ ]:
# 126
# 매개변수로 임의의 두 수를 입력받은 후 사칙연산(덧셈, 뺄셈, 곱셈, 나눗셈)의 결과를 리턴하는 함수..

In [ ]:
# 127
# 매개변수로 임의의 두 수를 입력받은 후 크기를 비교해서 출력하는 함수..

In [ ]:
# 128
# 팩토리얼을 리턴하는 함수를 만드시오
# 5! = 5*4*3*2*1

In [ ]:
# 129
# 두 정수 a, b를 입력받은 후, a를 b로 나눈 몫과 나머지를 각각 리턴하는 함수를 만들고 실행하시오..

In [ ]:
# 130
# 임의의 영문문자열을 입력받은 후 문자열 내에 자음의 수를 리턴하는 함수...
# 모음 = 'aeiou'

In [ ]:
# 131
# 임의의 수 세 개를 입력받은 후, 평균, 최대값, 최소값을 출력..
# 단 입력값이 수가 아니면 수를 입력하도록 메시지와 입력창을 출력..

In [ ]:
# 132
# 임의의 세 수 a,b,c 를 입력받은 후 a에서 b까지 c의 배수가 몇 개인지를 출력하는 함수..

In [ ]:
#133 lambda 함수와 list comprehension을 이용해서 1부터 20까지 정수의 제곱을 리스트에 담는 코드를 작성하시오.

In [ ]:
#134 두 리스트에서 각각 하나씩 원소를 받아서 튜플로 담아서 리스트에 담는 코드를 lambda 를 이용해서 작성하시오.

In [ ]:
# 135. 명함을 출력하는 class를 만들고, 객체를 생성하여 메소드를 호출하시오

In [ ]:
# 136,
# 원의 면적과 둘레길이를 출력하는 두 개의 메소드를 가진 클래스를 만들고, 객체를 생성하고, 메소드를 실행하시오..

# 클래스 변수 : pi = 3.14
# 반지름은 입력받는 인스턴스 변수 : r
# 원의 면적 : pi*r**2
# 원의 둘레 : pi*r*2

In [ ]:
# 137.
# print('can sing')을 출력하는 parent class를 만드고, 이를 상속하여 print('can dance')메소드를 갖는 child class를 만드시오

In [ ]:
# 138.
# class : FourCal
# 속성 : a, b
# 메소드 : 덧셈, 뺄샘, 곱셈, 나눗셈 - 4개의 메소드

# 위의 클래스의 객체를 생성하고 각각의 메소드를 호출하시오..